development:
  adapter: async

test:
  adapter: test

staging:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: scheduler_staging

production:
  adapter: redis
  url: <%= Rails.application.credentials.dig(:redis, :url) %>
  channel_prefix: scheduler_production
